"""empty message

Revision ID: 278d0c03b373
Revises: f0104e12b0f8
Create Date: 2022-12-12 17:47:35.099456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278d0c03b373'
down_revision = 'f0104e12b0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_database', sa.Column('completed_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_database', 'completed_time')
    # ### end Alembic commands ###
