"""empty message

Revision ID: 303396b5400c
Revises: d3ed249919e4
Create Date: 2022-10-04 17:46:59.417189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303396b5400c'
down_revision = 'd3ed249919e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo_database', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todo_database', 'todo_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_database', type_='foreignkey')
    op.drop_column('todo_database', 'category_id')
    op.drop_table('todo_category')
    # ### end Alembic commands ###
