"""cascade delete for TodoCategory and TodoList

Revision ID: 40182bf071c3
Revises: 8e30bc5d15a1
Create Date: 2023-03-16 22:29:46.609447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40182bf071c3'
down_revision = '8e30bc5d15a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('todo_database_category_id_fkey', 'todo_database', type_='foreignkey')
    op.create_foreign_key(None, 'todo_database', 'todo_category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_database', type_='foreignkey')
    op.create_foreign_key('todo_database_category_id_fkey', 'todo_database', 'todo_category', ['category_id'], ['id'])
    # ### end Alembic commands ###
