"""empty message

Revision ID: 55447dd72e8d
Revises: 
Create Date: 2022-09-29 19:42:52.459748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55447dd72e8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_database')
    # ### end Alembic commands ###
