"""empty message

Revision ID: 8e30bc5d15a1
Revises: 278d0c03b373
Create Date: 2022-12-12 18:10:20.968561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e30bc5d15a1'
down_revision = '278d0c03b373'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_category', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_category', 'create_time')
    # ### end Alembic commands ###
