"""empty message

Revision ID: 982eb44e639f
Revises: 303396b5400c
Create Date: 2022-10-04 19:23:40.854840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982eb44e639f'
down_revision = '303396b5400c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_database', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_database', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
