"""empty message

Revision ID: d3ed249919e4
Revises: 55447dd72e8d
Create Date: 2022-09-29 19:58:34.390579

"""
from asyncio.windows_events import NULL
from turtle import update
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ed249919e4'
down_revision = '55447dd72e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_database', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todo_database SET completed = False WHERE completed is NULL;')

    op.alter_column('todo_database', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_database', 'completed')
    # ### end Alembic commands ###
