"""empty message

Revision ID: f0104e12b0f8
Revises: 982eb44e639f
Create Date: 2022-12-06 20:22:22.667645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0104e12b0f8'
down_revision = '982eb44e639f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todo_database', sa.Column('expected_time', sa.DateTime(), nullable=True))
    op.add_column('todo_database', sa.Column('activity_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_database', 'activity_time')
    op.drop_column('todo_database', 'expected_time')
    op.drop_table('world_reminder')
    # ### end Alembic commands ###
